apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-nginx-service
spec:
  selector:
    app: {{ .Release.Name}}-nginx-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name}}-app-deployment
  labels:
    app: {{ .Release.Name}}-nginx-app
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app: {{ .Release.Name}}-nginx-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name}}-nginx-app
    spec:
      volumes:
        # Create the shared files volume to be used in both pods
        - name: shared-files
          emptyDir: { }
        - name: lara-config
          secret:
            secretName: {{.Release.Name}}-app-secret
            items:
              - key: ENV_VARIABLES
                path: .env
      containers:
      - name: php-app
        image: {{.Values.image_php.repository}}:{{.Values.image_php.tag}}
        volumeMounts:
          - name: shared-files
            mountPath: /var/www/html
          - name: lara-config
            mountPath: /var/www/html/.env
            subPath: .env
        lifecycle:
          postStart:
            exec:
              command: [ "/bin/sh", "-c", "cp -r /app/. /var/www/html && chmod -R 777 /var/www/html/storage"]
      - name: nginx-app
        #image: nginx:1.21-alpine
        image: {{.Values.image_nginx.repository}}:{{.Values.image_nginx.tag}}
        volumeMounts:
          - name: shared-files
            mountPath: /var/www/html
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name}}-app-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /api/$1
spec:
  rules:
    - host: {{ .Values.ingress.hostName}}
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name}}-nginx-service
                port:
                  number: 8080
