apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql-app
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-statefulset
#  labels:
#    app: mysql-app
spec:
  selector:
    matchLabels:
      app: mysql-app # has to match .spec.template.metadata.labels
  serviceName: "mysql-service"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: mysql-app
    spec:
      containers:
        - name: mysql-app
          image: {{.Values.db.image}}
          envFrom:
            - secretRef:
                name: {{.Release.Name}}-db-secret
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysqldb
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysqldb
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: standard
        resources:
          requests:
            storage: {{.Values.db.volume}}