apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}-db-secret
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "53"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.db.rootPass | b64enc | quote }}
  MYSQL_DATABASE: {{.Values.db.name | b64enc | quote }}
  MYSQL_USER: {{.Values.db.user | b64enc | quote }}
  MYSQL_PASSWORD: {{.Values.db.pas| b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}-app-secret
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "54"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  ENV_VARIABLES: |
    {{ .Values.app.envVariables | b64enc }}